artifact_location: file:///C:/Users/dango/OneDrive/Desktop/mowingestimator/MLFLOW_TRACKING_URI/0/models/m-3b2097448a8b49e2b458fa58abd2564d/artifacts
creation_timestamp: 1760996903620
experiment_id: '0'
last_updated_timestamp: 1760996910007
model_id: m-3b2097448a8b49e2b458fa58abd2564d
model_type: null
name: model
source_run_id: dbd8d6d71e5f4a7dac217f9f7ef024bc
status: 2
status_message: null
