artifact_location: file:///C:/Users/dango/OneDrive/Desktop/mowingestimator/MLFLOW_TRACKING_URI/0
creation_time: 1760996902270
experiment_id: '0'
last_update_time: 1760996902270
lifecycle_stage: active
name: Default
